### ISSUE TITLE
Issues with Kali setup

### ISSUE THREAD

**Issue by alexlomas** [SecurityJon/PiKey#1]
I'm running the setup as per instructions:

bash <(curl -s https://raw.githubusercontent.com/SecurityJon/PiKey/master/server/install.sh) as root under Kali.

I get the following error:

++ Modifying SSH to prevent Root Login for Security
++ Creating Required User
-+ User pikeyuser already exists, skipping
++ Creating Security Keys
-+ SSH Public Key already exists, deleting
++ Creating SSH Public Key
Paste in the SSH Public Key generated during the client install >
<snip>
++ Inserting Public Key into File
++ Changing Permissions on Files
++ Downloading PiKey
Cloning into '/tmp/PiKey'...
Username for 'https://github.com': xxx
Password for 'https://xxx@github.com':
remote: Repository not found.
fatal: repository 'https://github.com/my-wii-is-on-fire/pipasswordhacking.git/'  not found
++ Moving Files
mkdir: cannot create directory ‘/home/pikeyuser/PiKey’: File exists
mv: cannot stat '/tmp/PiKey/PiKey/server/serversidescript.py': No such file or directory

**Comment by SecurityJon** [comment]
Apologies, I forgot to adjust the scripts (and test them) when we moved from a dev repo.

I've done a bit of cleanup now and both client and server should be working correctly.

**Comment by alexlomas** [comment]
The client installer still seems to have some broken directory references. For example:

mv: cannot stat '/tmp/PiKey/PiKey/client/blinktimport.py'

(An extra PiKey/)

**Comment by SecurityJon** [comment]
Another remnant from the old scripts (and I can't test from where I am).

All 'double PiKey' references now fixed in the client installer.

**Comment by sowhatsecurity** [comment]
Just re-ran the installers for both the client and the server and the changes appear to have fixed the issue.
